### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by John4650-hub** [DonDejvo/Lancelot#7]
Hi, we need a guide on how to use this game library like how to configure a new scene, add collision, set world bounds , use the camera, load in assets, add gravity, play animations, working with user input etc... Lastly provide some basic examples which can demonstrate  it's usage. Thanks

**Comment by DonDejvo** [comment]
Sorry for late reply, the library is still under development and the structure might change by time and I am now trying to fix bugs, at least the most serious, I did during the time.
I plan to write guide after I feel it is more stable.
May I know how did you find about my library?

**Comment by John4650-hub** [comment]
I will wait then. Also you told me about your library at  sololearn, remember  the person who asked you for advice on how to start building games, that was me.
